"""add kind in visit

Revision ID: 33bd8a99c52
Revises: 1912beb3fc7
Create Date: 2015-10-31 12:43:27.018878

"""

# revision identifiers, used by Alembic.
revision = '33bd8a99c52'
down_revision = '1912beb3fc7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('kind', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_visit_kind'), 'visit', ['kind'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_kind'), table_name='visit')
    op.drop_column('visit', 'kind')
    ### end Alembic commands ###
